### ISSUE TITLE
After upadate to 0.8.4, show error:  Request initialize failed with message: this.send is not a function

### ISSUE THREAD

**Issue by mgoku** [bmewburn/intelephense#101]
This morning I update PHP Intelephense to version 0.8.4.

After I reload vscode, an error dialog shown with message `[PHP Intelephense] Request initialize failed with message: this.send is not a function`.

Here is the developer console output

![screenshot_20171218_084233](https://user-images.githubusercontent.com/1448244/34086588-7fe5464e-e3cf-11e7-9581-40cc66cbecf0.png)

VSCode 1.9.0
OS: Linux

**Comment by bmewburn** [comment]
This error has appeared before when the cache is corrupted. You could try setting `"intelephense.trace.server" : "verbose"` and looking for the initialize request output. There will be a `storage` path property. You can delete all extension specific data in this folder to clear the cache (There is a clear cache command too but it may be unavailable if the extension has crashed). If you can, post any relevant info in this ticket that you might see in the trace.

**Comment by mgoku** [comment]
Clean the cache does fix this problem. Thank you.

I change `"intelephense.trace.server" : "verbose"`, but there does't seem any relevant information regarding this specific issue.  The trace output on intelephense only give

```
[Trace - 11:20:54] Sending request 'shutdown - (1)'.
[Trace - 11:20:54] Received response 'shutdown - (1)' in 3ms. Request failed: Request shutdown failed with message: this.send is not a function (-32603).
```

**Comment by jplew** [comment]
I got the same error message, and @bmewburn's solution of deleting the storage folder solved it. 

In case it helps anyone, my storage folder (on MacOS X) was located here: 

`~/Library/Application Support/Code/User/workspaceStorage/f272d2ae0b5da78186ec33702ed090ce/bmewburn.vscode-intelephense-client`

**Comment by slawisha** [comment]
ubuntu

~/.config/Code/User/workspaceStorage

**Comment by alexandredevserra** [comment]
Windows 10

C:\Users\UserName\AppData\Roaming\Code\User\workspaceStorage

**Comment by Bwaaahhh** [comment]
i solve this error in vscode. You need write " Intelephense: Clear Cache and Reload ".

**Comment by MAChitgarha** [comment]
@Bwaaahhh To complete your answer:
After installing and enabling Intelephense, go to "View > Command Palette..." (Ctrl + Shift + P). Then, enter `Intelephense: Clear Cache and Reload` and press Enter. Your VSCode should be restarted and the problem should be fixed. :)
