### ISSUE TITLE
Go to File / Quick Open no longer shows files in /vendor

### ISSUE THREAD

**Issue by jrseliga** [bmewburn/intelephense#102]
**Code**: 1.19
**Intelephense**: 0.8.4

Quick open `Ctrl+P` / `Cmd+P` is not populated with files in the `/vendor` directory anymore.

However, if a file in `/vendor` is opened once, it then is available in the Go to File / Quick Open dialog.

Go to definitions, use imports, etc. work fine.

**Comment by jrseliga** [comment]
I've also tested a clean install on a separate machine, same behavior.
On that machine, I reverted to Code 1.18.1 on a separate PC and the files are shown as expected.

**Comment by jrseliga** [comment]
Also noticed this is not limited to `/vendor`, in one project we use a `/workbench` directory to allow a composer package to be developed alongside a consuming app and autoload the classes in the downstream app's `composer.json`. These files also don't show up in `Ctrl+P` but do in `1.18`.

**Comment by alnutile** [comment]
Same problems as above, on Mac, was working prior.

**Comment by bmewburn** [comment]
Does it still occur when launching with this extension disabled? `code --disable-extensions`.
The quick file open is not provided by this extension and is an inbuilt vscode service. You may need to file your issue there.

**Comment by jrseliga** [comment]
I checked out the vscode repo, already an [issue reported](https://github.com/Microsoft/vscode/issues/40272).

Setting `search.useRipgrep` to `false` has resolved the issue, not aware if there are consequences in doing so, but at the moment file discovery wins.
