### ISSUE TITLE
Doesn't always run

### ISSUE THREAD

**Issue by jrseliga** [bmewburn/intelephense#103]
**Code**: 1.19
**Intelephense**: 0.8.4

Many times the extension does not run, and when attempting to clear the cache and reload (or execute any of the available commands) this error is received.

`command 'intelephense.clear.cache' not found`

**Comment by bmewburn** [comment]
Thanks for reporting. There's a bug in the workspaceContains activation event glob. Will be fixed in next release. In the meantime it should activate upon opening a *.php file

**Comment by bmewburn** [comment]
resolved in v0.8.5
