### ISSUE TITLE
Add a way to remove cached data

### ISSUE THREAD

**Issue by Paviluf** [bmewburn/intelephense#105]
Hello,

It will be great if we could easily delete the cached data for old project. It seem to usually take around 200MB for a Symfony project.

Thanks !

**Comment by bmewburn** [comment]
There's a command for that -- Clear cache and reload :)

**Comment by Paviluf** [comment]
I didn't knew that. Thanks !
It clear only the cached data of the current project ?

**Comment by bmewburn** [comment]
Yes, just the opened workspace
