### ISSUE TITLE
Allow paths to be ignored

### ISSUE THREAD

**Issue by scottsb** [bmewburn/intelephense#108]
It would be helpful to allow paths to be ignored entirely by Intelephense, as there may be code within the folder that is not actually used. For example, Magento 2 ends up duplicating its setup code in two places (fault of the framework, I know), but that means Intelephense gets confused about which of the two files (with the same fully qualified class name) to actually find a symbol.

**Comment by bmewburn** [comment]
You can do this using the vscode `files.exclude` or `search.exclude` settings

**Comment by scottsb** [comment]
Ah, didn't realize that would work. Thanks. That would meet my personal needs, but I can imagine it may not cover every case, so I won't close this myself. Not sure if you still think it would be worth implementing at some point or not.

**Comment by bmewburn** [comment]
I think it would be useful to have a separate exclude setting as there may be cases where editor search functionality is wanted but intellisense is not.

**Comment by SailorMax** [comment]
@bmewburn 
I have in `search.exclude` list value `"tmp/**/*": true,`
But in Output panel `Intelephense` write:
```
[Warn  - 09:44:59] file:///d%3A/max/Documents/GitHub/project/tmp/%21private/private/combined.php exceeds maximum file size.
```

Looks like something wrong and Intelephense still read some exclude directories :/
VSCode 1.12.0
Intelephense 0.8.5

**Comment by ottopic** [comment]
Hello I have a big problems of folders indexing.
I'm using VS Code 1.30.2 on Mac OS 10.14.3 and my work's folder is on samba server.
```
/Volumes/space/libs/
/Volumes/space/commons/
/Volumes/space/Works/project1/
/Volumes/space/Works/project2/
```
I work on "space" volume but I don't need to index all folders because there are too many files.

I tried configuring Watcher Exclude and Search Exclude but indexing go on and causing traffic congestion on server.

```
"search.exclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
"files.watcherExclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
```
How can I solve it?

**Comment by two-bridges** [comment]
@ottopic  `files.exclude: {...}` should work.  

This will also exclude targetted files from Explorer altogether.  Maybe not ideal, depending on your use case.  

I see that this issue was already labelled for enhancement, so it may be addressed in future with a new setting or something.

**Comment by ottopic** [comment]
> @ottopic `files.exclude: {...}` should work.
> 
> This will also exclude targetted files from Explorer altogether. Maybe not ideal, depending on your use case.
> 
> I see that this issue was already labelled for enhancement, so it may be addressed in future with a new setting or something.

In my case I can't exclude files, I need to exclude unnecessaries paths.

**Comment by bmewburn** [comment]
`files.exclude` will accept globs that match directories or multiple files.

**Comment by ottopic** [comment]
@bmewburn I already configured, but it seems the scan go on. How can I check if the scan is by intelephense?

**Comment by bmewburn** [comment]
You could disabling extensions one by one

**Comment by ottopic** [comment]
Ok, I'll check.

**Comment by bmewburn** [comment]
there's now `intelephense.files.exclude`
