### ISSUE TITLE
Signature hint shouldn't disappear on space

### ISSUE THREAD

**Issue by ghost** [bmewburn/intelephense#111]
The signature hint for functions appears as it should when the comma is pressed in a list but it disappears when we start typing the argument.

The behavior of VS Code's built-in autocomplete is that the hint remains visible at any place inside the argument value. I believe this used to be intelephense's behavior as well but was changed in df6be2d.

If it isn't possible to reliably keep the hint open inside the value itself, would it be possible to ignore white spaces after the comma/parenthesis?

Version: 0.8.5

**Comment by bmewburn** [comment]
Yeah, I agree there's something weird happening here. I'm not sure why it is closing the help on space. The trigger characters are `(` and `,` so I'd assume that a call to fetch the parameter data only happens on these.

**Comment by bmewburn** [comment]
Fixed in next release

**Comment by bmewburn** [comment]
I reverted df6be2d but still see this intermittently. Also the popup sometimes doesnt close when outside of an argument list.

**Comment by mikolino** [comment]
I confirm that the tooltip stays open if we move the cursor to the left beyond the arguments (in the function name) and it disappears once we're past the function name.

But to me this is still a major improvement, thank you very much!
