### ISSUE TITLE
Bad autocomplete when i use namespace class or static class

### ISSUE THREAD

**Issue by Kcko** [bmewburn/intelephense#114]
Hi @bmewburn , 

I have class with namespace , see: https://goo.gl/1m6B7J
(namespace: Nette\Diagnostics  , class: Debugger,  method: barDump)

In another class (ProjectPreseterClass) im calling this NS and get full list of variables of ProjectPreseterClas and its not exist relevant suggestion for Debugger class, see: 

**(My personal opinion is that should offer namespaces under Nette namespace at first and then classes in Nette namespace. Does it make  sense? :))**

1) https://goo.gl/EjXuY6
2) https://goo.gl/yfXwhx
3) https://goo.gl/votY2T  (Debugger is in list, but after local variables of ProjectPresenterClass, its not good suggestion, and further it would be good to differ it with a special icon (to be clear that it is a class, not a variable))
4) https://goo.gl/Xeucvp (where are methods for Debugger class? Again somewhere behind local variables of ProjectPresenterClass),

This behavior is not very good and intuitive, is possible to change or set it?

====
Same problem with Singleton Class

See: https://goo.gl/AJNp3i
and calling in another php file https://goo.gl/Z1RBXe (no suggestion)

Thx for explanation. 

PS. Of course I appreciate your work, but it would be great to improve it.

**Comment by bmewburn** [comment]
Thanks for reporting. Most of the suggestions in the list look like they are not coming from this extension. I suggest setting `"php.suggest.basic": false` and disable any other php intellisense extensions to get a clearer picture of what is happening here. Also make sure to open vscode in folder mode so that all relevant project files are indexed. In saying that though there are some issues that can be worked on.

When using the extension you can just start typing the name of the symbol without the namespace to get a list of completions, it will then complete to the fully qualified name or the shortened name and automatically add a use declaration to the top depending on settings. I will look at enabling suggestions for fqns though as this was an oversight because of the focus on the above use case.

For your singleton class there is currently a limitation to the type inference where return expressions are not considered. This is being worked on but for now it relies on return type declarations or phpdoc.

**Comment by Kcko** [comment]
Hi @bmewburn ,

at first thanks for your fast reply.

Static classes or singleton are bad concept and and it does not matter that it does not work quite well.

Im using only ur extension for PHP because I think that works best from all php intelisense at market place :)

`php.suggest.basic": false` i already set.

I turn off extension from @ecmel (HTML CSS support) and now i dont see "mess" in PHP suggestion
see screenshot:  https://goo.gl/4msF5k  , with HTML CSS extension see: https://goo.gl/yPn2Hb 

Meanwhile, I see the main problem that it does not do suggestion for namespaces and class in namespaces.

Classes under Nette namespace eg: Cache (https://goo.gl/w4gZ4x), Http (https://goo.gl/REomsq) etc
result in some Controller / Presenter https://goo.gl/9tUr1t  (not working)

Any idea or is it in process?

Thx for feedback.

**Comment by bmewburn** [comment]
Suggestions when typing out the full namespace are not working, but you can use the short name of the class ( ie without the namespace).

![nette](https://user-images.githubusercontent.com/5885195/35327500-d24e90c0-014d-11e8-88e0-3dc53bdec2b9.gif)

**Comment by Kcko** [comment]
@bmewburn 

Thx, good to know.
What is problem when you typing full namespace and its not working, this is some limitation of VS Code or its a difficult to implement?

Some PHP IDE works fine (PHP Storm eg). 

I know that VSC is not IDE, I'm just only  interested in it and it's a shame.

**Comment by bmewburn** [comment]
It is easy to fix, the symbols are actually being returned from the extension. It's just that the label is wrong -- only showing the short name -- so vscode hides it because it doesn't match what is being typed. The completion item label just need to be changed to the fqn in such cases.

**Comment by Kcko** [comment]
I'm not sure that i  understand it well how try to explain me.
so could you fix it? 

Because in previous comment you show hot so partialy solve, but Nette Framework or Symphony has many namespaces and classes and I would love to see it via suggestion :-)

**Comment by Kcko** [comment]
Hi @bmewburn ,
you have partially right.
see Nette API https://api.nette.org/2.4/

my idea is such (I hope I do not want something nonsensical or unrealistic)

When I write Nette\  (i will see https://goo.gl/uCBMBF) namespaces under Nette
continue: Nette\Application\  i will see https://goo.gl/sbqKuS
continue: Nette\Application\UI\  https://goo.gl/hdg6Di  (now i will see classes under NS) https://goo.gl/Dbt6wF

You have partially right when i type Cache or some existing class in API  is sufficient, but i dont know all clasess, and this "FEATURE" will really help (I'll see everything under basic NS or concrete NS .. all child NS and their classes).

Is it understandable?

**Comment by bmewburn** [comment]
ok, I understand. It would be like the suggestions currently available in the namespace declaration (below), but available for classes etc. My concern is it could clutter up the completion list, but it is achievable, I will give it some more thought.

![nette-ns](https://user-images.githubusercontent.com/5885195/35387390-a733e094-0223-11e8-96bb-322b4b7cab74.gif)

**Comment by Kcko** [comment]
Yes, looks cool!!!!! 
But suggestion should work without first letter :-)
Nette\Application\ + tab  (All NS under this parent NS)

And searching classes will work the same way?  (it works great)

**Comment by bmewburn** [comment]
Available in next release.
![ns_completion](https://user-images.githubusercontent.com/5885195/36057754-db320976-0e66-11e8-8d13-17123594365c.gif)

**Comment by Kcko** [comment]
Next release will be launched when? 
Relase of  VSC plugin depends on release VSC editor or not?
