### ISSUE TITLE
Standalone usage?

### ISSUE THREAD

**Issue by josecanciani** [bmewburn/intelephense#115]
I would love to use your server for other projects like vim or sublime.

Is it possible to run it with stdio or tcp support? It would be nice if the project includes such a possibility out of the box. If not, can you point me out to a similar implementation I can use?

Thanks!
Jose

**Comment by josecanciani** [comment]
https://github.com/tomv564/LSP/issues/259

**Comment by bmewburn** [comment]
Thanks for your interest, I'd like to see it used in other editors. The current limitation is that this is a lib that needs to be wrapped in a server layer that handles the language server protocol. I use this for vscode - https://github.com/Microsoft/vscode-languageserver-node/tree/master/server. I'm not sure how vscode specific it is, I suspect very little despite the name. 

See https://github.com/bmewburn/vscode-intelephense/tree/master/server for the vscode intelephense server that uses the above package. Theres some package.json compile and watch scripts specific to vscode extensions but apart from that this may even be able to be used as is if you have a client that can spawn the server and make lsp calls to it.

**Comment by josecanciani** [comment]
Thanks for your reply! I saw that file earlier and notice it uses IPC instead of tcp, so I'm not sure if it can be accesed outside node. I assume the Connection object must accept any stream based object, it may accept a tcp pipe or something like that. I'll see what I can do (when I get some time of my work :P)

**Comment by bmewburn** [comment]
see https://github.com/Microsoft/vscode-languageserver-node/blob/master/server/src/main.ts#L1473, looks like there are a few options when creating connection - pipe, socket, stdio .

**Comment by josecanciani** [comment]
Thanks! I'll give it try

**Comment by bmewburn** [comment]
@josecanciani also, if you have success with using vscode-intelephense/server as is, I'm happy to drop the IPC params (so it defaults to whatever flags are used when spawning) and publish as a separate package so there is a universal solution for any editor. Good luck!

**Comment by josecanciani** [comment]
@bmewburn I had partial luck, the server is working but there are some errors which I'm not sure are from the client or the server (see https://github.com/tomv564/LSP/issues/259#issuecomment-361000909 ). I'm waiting from LSP sublime plugin creator feedback, but feel free to take a look, maybe by looking at the output you see something familiar.
