### ISSUE TITLE
Uppercase writing of true false null

### ISSUE THREAD

**Issue by theHactar** [bmewburn/intelephense#117]
Hey @bmewburn,

I noticed that in https://github.com/bmewburn/intelephense/commit/5ddd19c4072509990f382c9ae377aeb32cba9da3 you made `true` `false` and `null` all lowercase, in https://github.com/bmewburn/intelephense/commit/d08eb9cbfb10cfd5b2565acfc3ca946f6cb505cf this change got reverted.

I'm not sure if this was your intention, the lowercase `true` `false` and `null` would follow [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#25-keywords-and-truefalsenull).

I really enjoy working with in intelephense in VSC, so I thought I make you aware of this, my apology if this something that you are already aware of.

**Comment by bmewburn** [comment]
Looks like I changed the build version rather than the src 😆 Thanks for reporting!
