### ISSUE TITLE
question: is it possible to infer type on a variable

### ISSUE THREAD

**Issue by G3z** [bmewburn/intelephense#118]
I'm using Laravel and while using tests I do use a lot of factories

```php
$c = factory('App\Customer')->create();
```
i tried to infer type with a comment `/* @var $c App\Customer */` but it doesn't work
is there a simple way to tell Intelephense that `$c` is an `App\Customer` instance ?

**Comment by arturock** [comment]
`/* @var \App\Customer $c */`

**Comment by bmewburn** [comment]
@arturock almost has it `/** @var \App\Customer $c */` . Only phpdoc format is supported.

**Comment by arturock** [comment]
Ups! I answered in a rush and didn't realize the missing asterisk, Thanks @bmewburn!
