### ISSUE TITLE
Doc block info on hover

### ISSUE THREAD

**Issue by bfranklyn** [bmewburn/intelephense#124]
Would it be possible to get doc block information on hover, like in the following screenshot?
 
![2018-03-02](https://user-images.githubusercontent.com/6205670/36893598-a9bb650c-1dd6-11e8-99c9-bb90253dc3b1.png)

Method and param descriptions etc.

**Comment by Azeirah** [comment]
I've taken a short look at this, in [hoverProvider.ts](https://github.com/bmewburn/intelephense/blob/1d2fabf51ea4529ed063022ab7f3d7ebdfc9b0b5/src/hoverProvider.ts#L48), the `contents` value is what is being displayed on actual hover events.

I'm not entirely sure where the documentation blocks are stored, but I do believe they're available somewhere in any of the variables in `hoverProvider.ts`'s scope.

All that's needed afterwards is to just add it to the contents array.
