### ISSUE TITLE
Const visibility (PHP 7.1) unsupported?

### ISSUE THREAD

**Issue by mindplay-dk** [bmewburn/intelephense#126]
I'm getting an error message for a declaration like the following:

```php
<?php

class Foo
{
    public const BAR = 'hello';
}
```

The error output is as follows:

    syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

Class constant visibility modifiers [are supported as of PHP 7.1](https://wiki.php.net/rfc/class_const_visibility).

Is there any way to specify the language level? (similar to how this is configurable in PHP Storm?)

If not, what version of PHP is officially supported by Intelephense? If only a single language level is supported, perhaps the currently supported version should be stated somewhere.

(Perhaps the language level could be inferred from `composer.json`?)

**Comment by mindplay-dk** [comment]
[Nullable type-hints](http://php.net/manual/en/migration71.new-features.php) also don't appear to be supported.

**Comment by bmewburn** [comment]
These errors may be coming from the built-in vscode PHP linter. Intelephense diagnostics are prefixed with `[intelephense]`

**Comment by mindplay-dk** [comment]
> These errors may be coming from the built-in vscode PHP linter

I'm not at my work machine right now, but fairly certain the first thing I did was turn off the built-in PHP support. Maybe I only disabled the built-in auto-completion?

Either way, these messages didn't have the `[intelephense]` prefix, so not coming from your plugin 👍
