### ISSUE TITLE
Auto-completion on underscore

### ISSUE THREAD

**Issue by shutchinson** [bmewburn/intelephense#128]
When working with functions that have underscores in them, such as `array_map()`, it only auto-completes sometimes.

If you autocomplete a function, then delete it, and try to re-type to autocomplete the previous function, it works.

See [video example](https://drive.google.com/file/d/1JRjkFYyEqezbJ1DW-tb4_mEyOMg2hsY4/view?usp=sharing)

- Ubuntu 18.04
- Same thing happens on `code` and `code-insiders`
- `"php.suggest.basic": false`

**Comment by bmewburn** [comment]
I'm experiencing the same on Debian. Are you sure it's because of the underscore though? When I try `str_pad` or `str_replace` it works ok. It looks like it stops matching after `arra|` as the `y` doesnt get highlighted. I wonder if this is a vscode issue as it is responsible for filtering the set.

**Comment by shutchinson** [comment]
@bmewburn missed this. Will check it again tomorrow and report back.
