### ISSUE TITLE
Externally defined phpdoc

### ISSUE THREAD

**Issue by aNickzz** [bmewburn/intelephense#133]
I've been enjoying the phpdoc functionality, due to the number of magic methods and fields defined by the ORM I'm using, in this case, SilverStripe. However, there's a large number of classes in composer dependencies that don't have phpdoc defined. Additionally, in SilverStripe, there are Extension classes that define additional methods and fields on class types, similar to traits, but exactly. Extension classes are usually added by other packages than the one they're extending, so it doesn't make sense to phpDoc the added magic methods and fields added by extensions to the target class itself.

It would be very useful if a class' documentation could be defined/extended in other files. [Relevant SO question](https://stackoverflow.com/questions/38947803/can-you-create-an-external-phpdoc-for-a-class).

A potential example usage:
Foo.php included by dependency `composer require example/foo`:
```php
/**
 * @property bool $Bar
 */
class Foo extends DataObject {
  private static $db = [
    'Bar' => 'Boolean'
  ];
}
```

FooExtension.php either in project code or another dependency
```php
//In this case its relevant to include the extension doc in FooExtension.php, but it could be defined with a bunch of other doc extensions in a 'phpdoc.php' too
/**
 * @class \Foo
 *
 * @property bool $Baz
 * @method null qux()
 */

/**
 * FooExtension added to Foo via a config.yml elsewhere
 */
class FooExtension extends DataExtension {
  private static $db = [
    'Baz' => 'Boolean'
  ];
  public function qux() {
    //...
  }
}
```

This way you could get full autocomplete for `Foo` without having to fork/modify the "example/foo" package.

**Comment by bmewburn** [comment]
You should be able to create a stub file to include the additional methods. It would need to have the same class name.

```php
class Foo {
  private static $db = [
    'Baz' => 'Boolean'
  ];
  public function qux() {
    //...
  }
}
```
