### ISSUE TITLE
Anonymous functions' symbol names are not user friendly

### ISSUE THREAD

**Issue by garrettw** [bmewburn/intelephense#144]
Being that I have Code Outline installed, I am able to see a list of all functions in a given file. Intelephense seems to have the best symbol provider, but it reports anonymous functions' names as "#anon#file://path#line_number" which is horribly unwieldy.

Could this be changed to something easier to read? I propose making it either "#line_number" or ":line_number". The filename is probably irrelevant because the outline only shows what's in the current file, and the fact that such a function name begins with an illegal character should be enough to indicate that it's anonymous.

Also, if the anonymous function is created as a variable assignment, I think it would be great to prepend $varname to its symbol name and combine its listing with that of the variable somehow.

**Comment by jbiancovns** [comment]
there is a way to ignore this anonymous functions ?

**Comment by bmewburn** [comment]
Names are now more concise in 1.0. Ignoring the anon functions would mean all symbols in that subtree would also be ignored which is probably not desirable.
