### ISSUE TITLE
Zend framework classes support

### ISSUE THREAD

**Issue by tomiiq** [bmewburn/intelephense#151]
I have problem with classes in zend framework format. I have for example

class Skicentres_Model_Skicentres 	extends Skicentres_Model_Abstract {

and I cannot click to parent class and go to parent file. Link is working only after manual opening of parent file.

I dont know if it is issue for intelephense or my vs code missing some another extension, but this is very annoying.

**Comment by amadeann** [comment]
I think this may be a caching issue - happens to me all the time. Try to run `Intelephense: Clear Cache and Reload` command and see if it helps.

**Comment by bmewburn** [comment]
Yeah most likely cache. This has been improved in 1.0
