### ISSUE TITLE
Autocomplete doesn't work for ArrayAccess and Iterator

### ISSUE THREAD

**Issue by asvavilov** [bmewburn/intelephense#155]
Example annotation:
```
namespace Typography {
	/**
	 * EO_MaterialFormat_Collection
	 *
	 * @method void add(\Typography\EO_MaterialFormat $object)
	 * @method bool has(\Typography\EO_MaterialFormat $object)
	 * @method bool hasByPrimary($primary)
	 *
	 * @method void offsetSet() ArrayAccess
	 * @method void offsetExists() ArrayAccess
	 * @method void offsetUnset() ArrayAccess
	 * @method void offsetGet() ArrayAccess
	 * @method void rewind() Iterator
	 * @method \Typography\EO_MaterialFormat current() Iterator
	 * @method mixed key() Iterator
	 * @method void next() Iterator
	 * @method bool valid() Iterator
	 */
	class EO_MaterialFormat_Collection implements \ArrayAccess, \Iterator {}

	/**
	 * EO_MaterialFormat
	 *
	 * @method \int getId()
	 * @method EO_MaterialFormat setId(\int $id)
	 */
	class EO_MaterialFormat {}
}
```
Example code:
```
	$collection = new \Typography\EO_MaterialFormat_Collection();
	foreach ($collection as $item)
	{
		$item->...
	}
	$collection[0]->...
```
"$item" and "$collection[0]" have not detected as "\Typography\EO_MaterialFormat" type.

**Comment by kAlvaro** [comment]
I understand that type information should be obtained from `@method \Typography\EO_MaterialFormat current() Iterator` (or just `@method EO_MaterialFormat current() Iterator`), am I right?

While you can always use a type annotation like `/** @var \Typography\EO_MaterialFormat $item */` I agree it would be a nifty feature.

**Comment by asvavilov** [comment]
> I understand that type information should be obtained from @method \Typography\EO_MaterialFormat current() Iterator (or just @method EO_MaterialFormat current() Iterator), am I right?

Yes. This is how PHPstorm works.

> While you can always use a type annotation like /** @var \Typography\EO_MaterialFormat $item */ I agree it would be a nifty feature.

That's clear. It would be more convenient without unnecessary annotations.
This is nifty feature request. :-)
