### ISSUE TITLE
Starting client failed

### ISSUE THREAD

**Issue by jfeid** [bmewburn/intelephense#157]
Hi,

The PHP Intelephense extension fails to start with the following error:

> [Error - 10:16:21 AM] Starting client failed
Error: spawn /usr/share/code/code EMFILE
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Extension:
> bmewburn.vscode-intelephense-client version 0.8.8

VS Code:
> Version: 1.28.1
Commit: 3368db6750222d319c851f6d90eb619d886e08f5
Date: 2018-10-11T18:09:20.566Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by faelv** [comment]
Same problem, started today:

> [Error - 7:29:51 PM] Starting client failed
> Error: spawn /usr/share/code/code ENOENT
> 	at _errnoException (util.js:1024:11)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
> 	at onErrorNT (internal/child_process.js:372:16)
> 	at _combinedTickCallback (internal/process/next_tick.js:138:11)
> 	at process._tickCallback (internal/process/next_tick.js:180:9)

Extension:

> bmewburn.vscode-intelephense-client version 0.8.8

VS Code:

> Version: 1.28.2
> Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
> Date: 2018-10-17T00:20:56.183Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64

**Comment by faelv** [comment]
> Same problem, started today:
> 
> > [Error - 7:29:51 PM] Starting client failed
> > Error: spawn /usr/share/code/code ENOENT
> > at _errnoException (util.js:1024:11)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
> > at onErrorNT (internal/child_process.js:372:16)
> > at _combinedTickCallback (internal/process/next_tick.js:138:11)
> > at process._tickCallback (internal/process/next_tick.js:180:9)
> 
> Extension:
> 
> > bmewburn.vscode-intelephense-client version 0.8.8
> 
> VS Code:
> 
> > Version: 1.28.2
> > Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
> > Date: 2018-10-17T00:20:56.183Z
> > Electron: 2.0.9
> > Chrome: 61.0.3163.100
> > Node.js: 8.9.3
> > V8: 6.1.534.41
> > Architecture: x64

Problem found! My fault, there was a incorrect folder path (it was renamed) in my workspace file.

**Comment by bmewburn** [comment]
new version out, is this still occurring?

**Comment by jfeid** [comment]
Nope, seems to work fine now. Thanks!
