### ISSUE TITLE
variable declared on another file and subclass

### ISSUE THREAD

**Issue by yokowasis** [bmewburn/intelephense#160]
The definition / auto complete is only available for a variable that is declared on current file. 

If the variable is declared on external file , you can't use its autocomplete.

Is there a way to fix this ?

**Comment by tmjaga** [comment]
I have the same problem

**Comment by arturock** [comment]
Try reindexing your source with the 'Clear cache and reload' command

**Comment by tmjaga** [comment]
Does't help :(

**Comment by bmewburn** [comment]
Global vars are not currently supported. You can type hint with `@var DbOperations $db` in SomeClass.php as a workaround

**Comment by tmjaga** [comment]
Thanks for the advice.
But it will be great advantage to support this feature. 
F*ing slowly PHPStorm sipport it :(

BR,
Anatoly

**Comment by bmewburn** [comment]
As of version 1.0 this will work for variables declared with the global keyword.
