### ISSUE TITLE
Not work in VSC 1.28.2

### ISSUE THREAD

**Issue by kmvan** [bmewburn/intelephense#162]
VSC Version: 1.28.2
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:20:56.183Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
---------
Intelephense can not show other class name or function.

**Comment by kmvan** [comment]
And tested: works 1.27.2 and 1.28.1

**Comment by arturock** [comment]
Working for me on 1.28.2

**Comment by johnbillion** [comment]
Works for me too.

**Comment by benyaminl** [comment]
@kmvan do you exprience error on intelephense? Try to reload the cache and reload vs code. I've that problem not long ago, and the source of the problem is the index of the intelephense is broken and need to be reindexed.

**Comment by bmewburn** [comment]
Try reinstalling or the 'clear cache and reload' command
