### ISSUE TITLE
Indexing problem

### ISSUE THREAD

**Issue by MiladMohebnia** [bmewburn/intelephense#164]
there are php files in `./.fw/` directory and the files are not indexed. as I open each file it will be indexed. so my framework files are not index until I open them all one time.
I tried to add something like this but I know it's crazy :smile: 
```
"files.associations": {
        "**/.fw/**" : "php",
        "**/.fw/*.php" : "php",
        "**/.fw/**/*.php" : "php"
    }
```
can anyone help please. 
thank you.

**Comment by benyaminl** [comment]
is it in one project folder? I have my own fw and it works fine even I add composer library to my fw that soo deep in the folder.

**Comment by bmewburn** [comment]
Try the 'clear cache and reload' command from the command palette

**Comment by bmewburn** [comment]
closing as indexing has been refactored in v1.0.0
