### ISSUE TITLE
Enabling Intelephense on MacOS Mojave 10.14.3 causes CPU to +100%

### ISSUE THREAD

**Issue by lumbergh** [bmewburn/intelephense#170]
Before enabling Intelephense CPU processes are nominal...
<img width="1440" alt="screen shot 2019-01-28 at 8 58 28 am" src="https://user-images.githubusercontent.com/28716617/51852604-47d78680-22db-11e9-9135-f5a26e1b99ca.png">

After enabling Intelephense CPU exceeds 100% for the Code Helper process...
<img width="1440" alt="screen shot 2019-01-28 at 8 58 53 am" src="https://user-images.githubusercontent.com/28716617/51852695-73f30780-22db-11e9-8e10-bb93f5e56d2d.png">

VS Code Version: 1.30.2 (1.30.2)
MacOS Mojave 10.14.3 (18D42)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
Processor: 2.3 GHz Intel Core i5
Memory: 8 GB 2133 MHz LPDDR3

**Comment by ottopic** [comment]
It seems the indexing of files and folders... I have similar problem and I need to exclude folders from indexing too.

**Comment by bmewburn** [comment]
does the cpu return to normal after some time?
