### ISSUE TITLE
Remove Definitions from References

### ISSUE THREAD

**Issue by esemlabel** [bmewburn/intelephense#171]
Remove Definition from Reference list, since there are different.

Defined functions or methods should'n appear in reference list, because they'r not references and available from separate menu Go/Peek Definition or within shortcut.

**Comment by bmewburn** [comment]
Version 1.0 will respect the value of `ReferenceContext.includeDeclaration` which is sent with the `textDocument/references` request. In my tests vscode sends true for this value when finding references so definitions/declarations will be included. Please file an issue against the vscode repo if you think this should be changed.

**Comment by esemlabel** [comment]
Vscode [#68071](https://github.com/Microsoft/vscode/issues/68071)
