### ISSUE TITLE
Is there an ETA for v1.0 release? Or a way to build manually?

### ISSUE THREAD

**Issue by Talv** [bmewburn/intelephense#172]
It appears many issues have been closed and marked as `Resolved in 1.0` which sounds great, but it doesn't seem to be live yet. I wanted to give it a go, but I'm confused as to where the code with all these fixes is? 

Master branch wasn't updated for a long period. I've tried to clone & build `transform-refactor` as that one seems to be newest, but it failed:
```sh
~/dev/intelephense  transform-refactor ✗                                                                                                                                                                    322d ⚑  
▶ npm run build

> intelephense@0.8.8 build /home/kk/dev/intelephense
> npm run clean && ./node_modules/.bin/tsc -p ./tsconfig.json && cp ./src/builtInSymbols.json ./lib/


> intelephense@0.8.8 clean /home/kk/dev/intelephense
> rm -rf ./lib && mkdir ./lib

src/parser/phrase.ts(215,16): error TS4033: Property 'expected' of exported interface has or is using private name 'TokenType'.
src/transformers/symbolPass.ts(97,17): error TS1005: ')' expected.
src/transformers/symbolPass.ts(98,13): error TS1128: Declaration or statement expected.
```

So my question basically comes to: is there are anyway to test this upcoming version?

**Comment by bmewburn** [comment]
it's available now in npm and vscode marketplace

**Comment by Talv** [comment]
Oh, so it's like I've been afraid of - intelephse becomes a proprietary software and source code will remain closed.

https://github.com/bmewburn/vscode-intelephense/blob/413e609a52f313fc0d506746208217810926fa5b/LICENSE.txt#L27-L64

To me it basically means it's time to look around for an alternative... but thank you for all the good work till that point.

I believe many users would appreciate if you'd clarify what are your plans regarding the project. Will it become a paid extension at some point in the future?

**Comment by bmewburn** [comment]
I've closed the source while I decide what direction to take it. There may be a premium version in the future or I may open source it again. Either way, the current feature set of diagnostics, completion, parameter hints, go to definition, references, workspace symbols, document symbols, hover, highlight will always be free.
