### ISSUE TITLE
Complex curly expressions appear not to parse inside double quotes

### ISSUE THREAD

**Issue by amh15** [bmewburn/intelephense#173]
As I understand it, complex curly expressions inside double quotes are supposed to allow expressions like this:

$x = "{self::$args['time']} {self::$args['date']}";

This creates an error in VS code (Unexpected Unknown) at the single quotes.

Am I mistaken?

Thanks for intelephense!

**Comment by bmewburn** [comment]
Does it run? I get a fatal error when trying to execute this.
`PHP Parse error:  syntax error, unexpected '' (T_ENCAPSED_AND_WHITESPACE), expecting identifier (T_STRING) or variable (T_VARIABLE) or number (T_NUM_STRING)`

**Comment by amh15** [comment]
Well it seems you are correct. The complex curly format seems to be an error for static class members.

echo "{self::$x['test']}"; // causes error
echo "{$this->p['test']}"; // works

Thanks for the response and sorry to assume it was valid! I will perhaps make a comment on the relevant php.net page.

**Comment by amh15** [comment]
One of the comments on php.net already agrees with my original idea that it should work. Nevertheless as of today it does not compile.
