### ISSUE TITLE
Indexing folder problem on samba volume

### ISSUE THREAD

**Issue by ottopic** [bmewburn/intelephense#174]
Hello I have a big problems of folders indexing.
I'm using VS Code 1.30.2 on Mac OS 10.14.3 and my work's folder is on samba server.
```
/Volumes/space/libs/
/Volumes/space/commons/
/Volumes/space/Works/project1/
/Volumes/space/Works/project2/
```
I work on "space" volume but I don't need to index all folders because there are too many files.

I tried configuring Watcher Exclude and Search Exclude but indexing go on and causing traffic congestion on server. My server administrator will kill me if I don't stop that indexing :-) :-P .

```
"search.exclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
"files.watcherExclude": {
    "**/Volumes/space/commons/**": true,
    "**/Volumes/space/libs/**": true,
},
```
How can I solve it?

**Comment by bmewburn** [comment]
v1.0.0 has it's own exclude setting now `intelephense.files.exclude` that accepts an array of globs to exclude

**Comment by ottopic** [comment]
Great news, 1.0.0 is already released ?
