### ISSUE TITLE
Intelephense: Clear Cache and Reload

### ISSUE THREAD

**Issue by nopalnaxcpm** [bmewburn/intelephense#177]
Intelephense: Clear Cache and Reload

Command Was Not Found

**Comment by antoniopaisfernandes** [comment]
It has been renamed to 'Index workspace'.

https://github.com/bmewburn/vscode-intelephense/commit/b53210c11e020cbf7a70e53240369eb562f01513#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR45
