### ISSUE TITLE
sizeof: expected 2 arguments. Found 1.

### ISSUE THREAD

**Issue by Lennert-Onyx** [bmewburn/intelephense#184]
I updated the intelephense extension recently and I am getting errors all over my project.
Everywhere the sizeof() method is used, intelephense is complaining about expecting a second argument.
sizeof() does have 2 arguments, but the second is optional. Is this intentional?

**Comment by bmewburn** [comment]
This is coming from the stub files. PR submitted https://github.com/JetBrains/phpstorm-stubs/pull/518
