### ISSUE TITLE
Failed to apply changes

### ISSUE THREAD

**Issue by nkoporec** [bmewburn/intelephense#185]
After the update to 1.0.1, I can't use this extension. Indexing is not working at all, it will only index the current file (i have the files.associations and files.exclude set). Also anytime I want to save the file, I get an error: [Error - 11:58:45 AM] Failed to apply changes to ....

Also, by looking at the Output, on the same project the indexing took about 30-40 seconds on older version, now after the update, it says it took 8 sec.

I had to revert extension back to the older version to get it working properly.

**Comment by JDDoesDev** [comment]
This seems related to  #https://github.com/bmewburn/vscode-intelephense/issues/194

**Comment by bmewburn** [comment]
duplicate
