### ISSUE TITLE
Seems like this repo is dead, head over to https://github.com/bmewburn/vscode-intelephense/

### ISSUE THREAD

**Issue by zapling** [bmewburn/intelephense#189]
https://github.com/bmewburn/vscode-intelephense/

**Comment by charrondev** [comment]
Ah that was my cause of confusion. @bmewburn A notice in the description + an archival would probably help.

Github allows you to move issues if you're an admin of both repositories now which should help.

**Comment by xiaohuilam** [comment]
Nope, The reason is just that, the language server module (intelephense) is NOT open source anymore.
