### ISSUE TITLE
10006 type error

### ISSUE THREAD

**Issue by Koekoe** [bmewburn/intelephense#191]
Example: 
```php
public function work($a, array $b = null) {
     ...
    if(null !== $b){
         //do something with b
         $this->insert($b);
    }
}

function insert(array $data){}
```

This gives the error expected type "array" found "null" intelephense 10006

Also 
preg_match_all("//i", $text, $result))  : Expected array|null found null for $result 
catch(Exception $e) { $this->handle($e) } : found null

**Comment by bmewburn** [comment]
dup bmewburn/vscode-intelephense#211
