### ISSUE TITLE
Discover variables set by extract()

### ISSUE THREAD

**Issue by alextegelid** [bmewburn/intelephense#193]
It'd be great if there was a way to discover variables created with the PHP's `extract` function. I recognise that it may very well be hard (if not impossible), especially if the input to extract is a function which returns an associative array, as is the case with WordPress' [shortcode_atts function](https://codex.wordpress.org/Function_Reference/shortcode_atts).

The next best thing would be a way to ignore certain variable names that I know is being set by extract.

![image](https://user-images.githubusercontent.com/7058721/53297332-96fed180-381d-11e9-8ad7-998bacd2d996.png)

**Comment by bmewburn** [comment]
In 1.0.3 if there is an extract or require/include call then it is now assumed that all variables are defined. I think it's not possible to reliably discover actual variables imported by extract. Might be possible for require/include at some later date.
