### ISSUE TITLE
Wrong error for anonymous function

### ISSUE THREAD

**Issue by mihazs** [bmewburn/intelephense#197]
Hi, i've created an anonymous function and intelephense can not parse the correct number of arguments.
Like this:
![expected 3 arguments found 0](https://user-images.githubusercontent.com/3963793/53370615-f13a8800-392c-11e9-90ff-caab7cb2cba2.jpg)

It's a bug.

**Comment by bmewburn** [comment]
Are you on 1.0.3? Please check version under extensions -> PHP intelephense

**Comment by mihazs** [comment]
Ok, i've updated and the error is gone. Thanks for this amazing extension and for the support.
