### ISSUE TITLE
Autocompletion adds namespace to basic functions

### ISSUE THREAD

**Issue by Quik7** [bmewburn/intelephense#24]
Hi!

I don't know if it is an issue but each time i'm using autocompletion for basic functions they are namespaced. Is there any way to disable this feature for functions?

**Example:**
> file_get[ENTER] -> \file_get_contents

I'm waiting for more improvements and good luck!
_PS: Your extension beats other PHP intellisenses for VSCode_

**Comment by bmewburn** [comment]
Thanks for raising this. I'll give it some thought and see if this can be relaxed a bit. I intended for the backslash prefix to occur on autocompletion of global functions when a (non-global) namespace declaration is present to explicitly identify the function. 

Not having the prefix means the function FQN would resolve to `MyNamespace\file_get_contents` and two lookups would need to be done to retrieve the correct function. This is what [PHP](http://php.net/manual/en/language.namespaces.rules.php) does but intelephense currently does a single lookup only.

**Comment by davidfaber** [comment]
+1

**Comment by calebporzio** [comment]
+1 - any word on this?

**Comment by bmewburn** [comment]
resolved in v0.8.0. Config option `intelephense.completionProvider.backslashPrefix` can enable/disable
