### ISSUE TITLE
Not all methods are suggested

### ISSUE THREAD

**Issue by YMIndustries** [bmewburn/intelephense#26]
Hi,

I don't use PHP very often so I'm not able to provide as much detail as I'd like, but I'll try my best. I'm using Intelephense on my CakePHP project. I'm writing integration tests, and I noticed that Intelephense suggests methods such as $this->assertResponseOk() but not other methods, such as $this->assertEquals(). I suspect it's to do with the way CakePHP's integration test class inherits from PHPUnit's test class, but I wasn't able to reproduce the issue in a simplified example, so I'm not sure exactly where it's going wrong. I'm running CakePHP 3.4 with PHP 5.5.12 on Windows.

Thanks,

Josh

**Comment by anemitoff** [comment]
I had a similar problem... I am pretty sure that my problem is that the class I want suggestions for has more than 255 properties and methods exposed and the suggestions only cover the first 255.

**Comment by bmewburn** [comment]
Thanks for the reports. I've noticed similar behaviour. I think the symbol lookups in the inheritance chain are buggy in some situations. Will look at in v0.8.0

**Comment by bmewburn** [comment]
This has been heavily refactored in v0.8.0. Can reopen if there is still a problem
