### ISSUE TITLE
Issue with hinting @pram phpDoc.

### ISSUE THREAD

**Issue by endridev** [bmewburn/intelephense#27]
No intellisense for /** @param */ phpDoc comment.

**Comment by bmewburn** [comment]
Thanks for the report. Do you have a short snippet of code where @param is failing?

**Comment by endridev** [comment]
Thanks for the superquick reply. No. I'm not talking about phpDoc automplete. I'm talking about the actual hinting of the property which has @param comment on top of it. Sorry for being too ambiguous.

Here is an example:

class PDOWrapper
{
	/**
	 * @param PDO $pdo 
	 */
	protected $pdo; <-------- The @param suggest that the property $pdo would hint to PDO class  and auto-complete it's methods/properties
	
	public function __construct( $pdo )
	{
		$this->pdo = $pdo;
	}
	
	public function query( $statement = '' )
	{       
		$this->prepare = $this->pdo->prepare( $statement ); < ------- No completion for PDO prepare() method.
		return $this;
	}
        //.................. the rest .....................//

BTW ... This extension is amazing.

**Comment by endridev** [comment]
Well, my bad. This is embarrassing. I was using wrong phpDoc comment to typehint the variable. Working late at night isn't helping at all :). Keep up with the good work. This extension is making PHP devs life easier :).

**Comment by bmewburn** [comment]
No prob, I'm glad that you're finding the extension useful :)
