### ISSUE TITLE
same name function definition but in different files

### ISSUE THREAD

**Issue by angelsguigui** [bmewburn/intelephense#28]
i have functions that are named the same

PrintPage() in 

browser/printhelper.php
smartphone/printhelper.php

and browser/index.php calls PrintPage from browser/printhelper.php
but smartphone/index.php calls PrintPage from smartphone/printhelper.php

Is it possible for 
"Go To Definition" to detect multiple function definition and allow the user to choose which file to go to?

**Comment by bmewburn** [comment]
Looks like the language server protocol allows for multiple locations returned from a definitions request so this should be possible.

**Comment by bmewburn** [comment]
resolved in v0.8.0
