### ISSUE TITLE
When using Intelephense and PHP DocBlocker extensions they conflict

### ISSUE THREAD

**Issue by neufena** [bmewburn/intelephense#30]
When both plugins are active typing /** results in a comment block with 2 sets of */ at the end.  IE:

/**
 * Undocumented function
 *
 * @param string $url
 * @param array $params
 */ */

or 

/**
 * 
 */ */

Can something be done to make these extensions play nicely together?

**Comment by bmewburn** [comment]
Thanks for reporting, resolved in v0.7.0
