### ISSUE TITLE
Problem with extencion local history

### ISSUE THREAD

**Issue by zero2000** [bmewburn/intelephense#34]
Hi, I am a user of your extension and it is very good and fast but there is a problem. Also use the extension local history and when using it brings problems since that extension generates a .performance in the project and when Go to the definition or Peek Definition on anything that allows to see definition what it does is to go to the .history folder and See it from that, instead of seeing it from the project which is very confusing when trying to define, maybe they could put in the configuration a way to exclude folders as well, since as I comment that is very confusing. To not be by and if they could optimize the information since its write array only comes out that is without an example, but before installing the extension if the description came out and an example as well
$ ArrayName = array ('' =>,);

After very cool

Thank you

**Comment by bmewburn** [comment]
Can you exclude the .history directory using the vscode `files.exclude` setting?

**Comment by zero2000** [comment]
Hello, still with the same problem still detecting the files generated by the extension local history and also does not detect functions with the same name but in different classes. Check for other users to have the same problem. Thanks in advance.

**Comment by zero2000** [comment]
Look, I'll send the screenshot for you to see, In this case making the configuration that indicated and follows me, but instead of showing me all to go to definition only shows me the one and it is the folder excluded
![sin titulo](https://user-images.githubusercontent.com/3870686/27356507-56934f68-55d4-11e7-8cb5-e992d0ec1693.png)

**Comment by bmewburn** [comment]
Thanks, I've found the problem and will fix in v0.7.0

**Comment by zero2000** [comment]
Hello, update and test it. Still generating that error, here is the debug for you to see:

`[Debug - 8:19:14] onDidOpenTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/.history/modules/admision/conectaprueba2_20170626081811.php | 12.066 ms | 28.5 MB
[Debug - 8:19:19] onDefinition | file:///c%3A/xampp/htdocs/erpuniversity/newerp/class/med/med_parametros.class.php | {"line":44,"character":52} | 0.963 ms | 28.5 MB
[Debug - 8:19:19] onDidOpenTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/modules/admision/conectaprueba2.php | 11.452 ms | 28.3 MB
[Debug - 8:19:19] onDidCloseTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/modules/admision/conectaprueba2.php | 0.022 ms | 28.4 MB
[Debug - 8:19:20] onDefinition | file:///c%3A/xampp/htdocs/erpuniversity/newerp/class/med/med_parametros.class.php | {"line":44,"character":51} | 1.674 ms | 28.4 MB
[Debug - 8:19:20] onDidCloseTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/.history/modules/admision/conectaprueba2_20170626081811.php | 0.027 ms | 28.4 MB
[Debug - 8:19:20] onDidOpenTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/.history/modules/admision/conectaprueba2_20170626081828.php | 10.562 ms | 28.2 MB
[Debug - 8:19:22] onDidCloseTextDocument | file:///c%3A/xampp/htdocs/erpuniversity/newerp/.history/modules/admision/conectaprueba2_20170626081828.php | 0.023 ms | 28.2 MB`

**Comment by bmewburn** [comment]
Are you manually opening these .history files? Or using the local history commands to navigate and view them?
