### ISSUE TITLE
exceeds maximum file size error

### ISSUE THREAD

**Issue by neufena** [bmewburn/intelephense#38]
Some files are too large, a good example if the mpdf library (ie vendor/mpdf/mpdf/mpdf.php)

There should be an options to increase the max file size and to exclude certain files from indexing

**Comment by bmewburn** [comment]
Was it an error or warning? The default max file size is 1000000 B which can be set in `intelephense.file.maxSize`. The `files.exclude` setting can be used to exclude files from indexing.

**Comment by bmewburn** [comment]
no prob :)
