### ISSUE TITLE
Support for finding implementors of an interface/renaming

### ISSUE THREAD

**Issue by TobiasBales** [bmewburn/intelephense#4]
First off all, I just stumbled across this gem and can't tell you how pleased I am with it.
I tried https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense previously and it was slow and just didn't work properly for me, so far intelephense works great.

The things that so far stop me from using it as a full intellij replacement are:
a) finding implementors of an interface/subclasses
b) refactoring as in renaming functions etc

Are those things planned/are there currently any contribution guidelines in case of feeling adventurous?

**Comment by bmewburn** [comment]
Thanks for the feedback! The goal is to support all language protocol features where possible. An implementor provider should be possible without too much effort. Rename and find all references will likely be more involved and implementing those wont happen in the short term. I'd welcome any help, in the coming days I'll get together a contribution guideline and organise things somewhat.
