### ISSUE TITLE
Using @var PHPDoc to work out the type of a variable

### ISSUE THREAD

**Issue by jackwilsdon** [bmewburn/intelephense#43]
Is it possible to use `@var` to tell Intelephense what type a variable is? This doesn't seem to work;

```PHP
/** @var $variable \MyClass */
$variable = get_variable();
```

Typing `$variable->...` doesn't complete anything from `\MyClass` but instead from the return type of `get_variable`. This functionality would be useful when using a method which returns a generic object, as we can specify what subclass is being reurned.

---

The only way I can see to force the type is to cast the result, but that's not a very nice way to do it;

```PHP
$variable = (\MyClass) get_variable();
```

**Comment by bmewburn** [comment]
The type is expected before the var name 
`/** @var \MyClass $variable  */`

**Comment by jackwilsdon** [comment]
Oops yes, that's it!
