### ISSUE TITLE
Add Use Declaration problem

### ISSUE THREAD

**Issue by shustrik** [bmewburn/intelephense#44]
It often doesn't work . For example you can use this project https://github.com/webdevilopers/php-ddd. And try create some var  in CalculationController  for example ` $test = new \Example\Domain\Model\DormerCalculation();`

But if you try create var in DormerCalculation for example `$test =  new \Example\Infrastructure\UniqueIdGenerator();` it  works fine.

Thank

**Comment by bmewburn** [comment]
Thanks for reporting. Will resolve in v0.8.0

**Comment by fetzi** [comment]
Any focus on this issue?

**Comment by bmewburn** [comment]
use declaration can now be added automatically on completion which makes the manual command less useful. It can be enabled/disabled using the `intelephense.completionProvider.addUseDeclaration` setting. The add use declaration command is still available and has had some improvements.
