### ISSUE TITLE
Autoformat Adds extra new lines  in php

### ISSUE THREAD

**Issue by Hyperspaceru** [bmewburn/intelephense#45]
autoformatting add extra new lines after   ' //  } ' , every time i press alt+shift+f

example code with troubles:

 private function processCompatibility()
    {
        // foreach ($aSheet["compatibility"]["exist"] as $cellName=>$value){
        // 	$excelCell = mb_strtolower(processCell($oWorksheet->getCell($cellName),['type'=>'string']));
        // 	if (!strstr($excelCell,$value)){
        // 	}
        // 	}

    }

**Comment by timothyallan** [comment]
Related https://github.com/bmewburn/vscode-intelephense/issues/18

**Comment by bmewburn** [comment]
resolved in v0.8.0
