### ISSUE TITLE
Object autocomplete

### ISSUE THREAD

**Issue by mikkeyalias** [bmewburn/intelephense#47]
Sample class:
```php
class SQL
{
    static function factory($db)
    {
        return new self($db);
    }

    protected function __construct($db)
    {
        $this->_db = $db;
    }

    private $_select = null;

    public function select($select)
    {
        $this->_select = $select;
        return $this;
    }

    private $_from = null;

    public function from($from)
    {
        $this->_from = $from;
        return $this;
    }

    private $_where = null;

    public function where($array)
    {
        $this->_where = $array;
        return $this;
    }
}
```

Autocomplete ok:
![image](https://user-images.githubusercontent.com/29526833/28831219-4c8ececc-76d9-11e7-88fe-d50760689b35.png)

Autocomplete not working:
![image](https://user-images.githubusercontent.com/29526833/28831301-7c1913fa-76d9-11e7-9ddf-1fa02de7bf9a.png)

Autocomplete not working:
![image](https://user-images.githubusercontent.com/29526833/28831312-85d877dc-76d9-11e7-9e7a-10ec2ff208f0.png)

Autocomplete ok:
![image](https://user-images.githubusercontent.com/29526833/28831332-8f29518a-76d9-11e7-8c40-adedbd7797a6.png)

Autocomplete not working:
![image](https://user-images.githubusercontent.com/29526833/28831342-9553905c-76d9-11e7-8ca6-d1601c8d3ee4.png)

**Comment by bmewburn** [comment]
Thanks for reporting. The type resolution currently relies on phpdoc and/or explicit type hinting. It should be possible to expand this and inspect the actual return statement though.
