### ISSUE TITLE
Show only functions in 'Go To Symbol In File'

### ISSUE THREAD

**Issue by RivenCode** [bmewburn/intelephense#48]
Are there any plans to provide filtering options for the Go To Symbol In File panel? For me personally, I would like to hide all variables/constants etc from the list and just show functions, as this is what I'm usually after in this context. 

Looking at the file I'm currently working on, this would cut down the number of symbols displayed from 1536, to 190, which would help me hugely.

Keep up the good work, I think this is easily the best PHP parser extension for VS Code.

**Comment by bmewburn** [comment]
It's a good idea, perhaps one that is best implemented in vscode itself. There's a ticket open in the vscode repo that requests something similar https://github.com/Microsoft/vscode/issues/5605. For now you can type `:` and group the symbols by kind, though that still leaves all the symbols visible.

**Comment by RivenCode** [comment]
Ahh fair point. Thanks for the `:` tip, I didn't know about that one and as it turns out it displays methods above variables, so that's a good workaround.
