### ISSUE TITLE
Make format configurable

### ISSUE THREAD

**Issue by bmewburn** [bmewburn/intelephense#51]
From @TheColorRed

> Could there be a way to keep the braces on the same line when formatting.
> 
> For classes and methods/functions the brace gets moved to the next line, and I would like them on the same line.

**Comment by bmewburn** [comment]
It could be done, and I see the benefits in making this configurable but personally I'm against it. The reason being is you end up with many config options to add (or not add) whitespace here and there which is a pain to write, maintain and may not even seen by many users. I'd prefer to keep the library as a low config, no fuss solution and IMO PSR2 is good enough.

I think I hear the collective groan of disapproval from pedantic dev. leads and managers as I type this so will leave open for discussion. Perhaps someone will submit a PR...

**Comment by TheColorRed** [comment]
If you don't want many config options you could have a `phpconfig.json` file the stores the config like other plugins...

**Comment by bmewburn** [comment]
A config file would be a good way to go. Happy for someone to have a go at this.

**Comment by bmewburn** [comment]
Format can be disabled using lang server protocol dynamic registration in preference for a more configurable formatter. There are no plans to introduce further format config options in this lib
