### ISSUE TITLE
adding a configuration option for not registering the document formatting edit provider

### ISSUE THREAD

**Issue by jjtriff** [bmewburn/intelephense#53]
Hello: 

I was trying to modify your code:

1. adding a configuration setting in package.json:
`"intelephense.formatter.enable": {
					"type": "boolean",
					"default": true,
					"description": "Enable debug logging."
				}`
2. and asking for it before doing
`this._registeredHandlers.set(
			DocumentFormattingRequest.type.method,
			new LanguageFeature<TextDocumentRegistrationOptions>((options) => this.createDocumentFormattingProvider(options))
		);`
inside client.ts file.

but I'm not sure what will I get when doing 
`Workspace.getConfiguration(this._id)`

so I was trying to debug your extension, but I wasn't able to do it. Didn't make vscode to run in debug extension mode.

BTW: I think I'm mixing here code from two different github repos.

What I'm trying to ask is for a short guide to clone your repo, edit it, debug it, push it, and make a pull request.

Zanks in advanced

PS: this has to do with #46, so I can keep working using your wonderful extension

**Comment by bmewburn** [comment]
moved to bmewburn/vscode-intelephense#25
