### ISSUE TITLE
The symbols added by the stub can not be displayed

### ISSUE THREAD

**Issue by tiansin** [bmewburn/intelephense#56]
stub1:
class MY_Controller extends CI_Controller....
stub2:
class MY_Controller extends CI_Controller....

real class:
class MY_Controller extends CI_Controller{
 
}
use $this->  no show all members from stubs and real class!

**Comment by bmewburn** [comment]
From memory, $this will only resolve to a single class, so it's probably either fetching symbols in one of the stubs or the real class and will not combine all of them. Why do you have stubs of the same name as your class? What is the advantage of this?

**Comment by tiansin** [comment]
Thank you for your reply,I used php-intellisense before, but it's too slow.
I use the Codeigniter framework, but also the definition of the stubs, but the plug-in analysis will be defined in the stub class replaced by the system CI_Controller.It will make $this-> not what i expect.

**Comment by arturock** [comment]
Not really related to the stubs situation, but about slowness you can ignore directories configuring `files.exclude` for some vendor stuff you wont ever open

**Comment by bmewburn** [comment]
v0.8.0 will merge definitions from multiple classes of the same name which should solve your problem. For now if your framework stubs provide all definitions then you can add the vendor framework folder to `files.exclude` so the extension only detects the stubs.

**Comment by bmewburn** [comment]
Should be resolved in v0.8.0. Can reopen if there's still issues here
