### ISSUE TITLE
Format HTML inside PHP?

### ISSUE THREAD

**Issue by rgfx** [bmewburn/intelephense#59]
My HTML is jacked, any suggestions? Working with WordPress. Using vscode

![jacked](https://user-images.githubusercontent.com/2388078/31357561-7e677316-acff-11e7-9f1a-f3c9d64ce0af.jpg)

**Comment by bmewburn** [comment]
The formatter ignores everything outside of `<?php ?>`. Workaround is to change language setting in bottom right of vscode to HTML and format.

**Comment by rgfx** [comment]
Not ideal, but that works, thanks.
