### ISSUE TITLE
Intelliphense load only strict public scope defined methods

### ISSUE THREAD

**Issue by tehSLy** [bmewburn/intelephense#68]
I have a class, which contains static methods, but when im trying to autocomplete, or highlight available methods, it goes only with 3 of them(it's more than 40 in class definition, I believe), all of them are defined as `public static`. Other `public` by default methods are not got in the list.

**Comment by tehSLy** [comment]
Ehm, can I get a any comment on this?

**Comment by bmewburn** [comment]
Thanks for reporting. It got closed automatically when I merged the fix into master. This should be resolved now in v0.8.1

**Comment by tehSLy** [comment]
Okay, thanks! You're doing great job
