### ISSUE TITLE
Auto formatting irregularities

### ISSUE THREAD

**Issue by kilevvri1** [bmewburn/intelephense#69]
This is beginning to really bug me. When working with mixed for pure PHP, on saves, sometimes the auto-formatting goes crazy. Sometimes it is subtle but then there are times when it makes massive blocks of code illegible.

This is how I have my code formatted:

 ``` // Check if production or local environment
  if (!LOCAL)
  {
    $breadcrumbs = array('<a href="' . $base_url . '">' . $home . '</a>');
  }
  else
  {
    $breadcrumbs = array();
  }
```

Instead it formats it to this:
  

```// Check if production or local environment
  if (!LOCAL)
    {
    $breadcrumbs = array('<a href="' . $base_url . '">' . $home . '</a>');
  } else
    {
    $breadcrumbs = array();
  }
```

While I can still read that, it's not a leisurely read.

The above change in code is the subtle version. In more extreme cases the entire block would have extreme indentation on all lines making it unreadable.

It would be nice to have an option to stop the auto-formatting. My workaround right now is to disable the extension, reload VSCode and then save. This is tedious, especially when testing minute code changes.

**Comment by bmewburn** [comment]
There's still some bugs to fix in the formatter. It can be disabled via the `intelephense.formatProvider.enable` setting.
