### ISSUE TITLE
Formatting makes incomplete hints

### ISSUE THREAD

**Issue by ValeryFVV2002** [bmewburn/intelephense#70]
Example. This code:
```php
$res = test($in);

function test($in)
	{
	$out = preg_replace("/.*/", "+++", $in);
	return $out;
	}
```
or this:
```php
$res = test($in);

function test($in){
	$out = preg_replace("/.*/", "+++", $in);
	return $out;
}
```

It shows the complete tip (mouse + CTRL). Its very comfortably. See pic
![No formatting](http://ipic.su/img/img7/fs/kiss_21kb.1510512645.png)

But, after formatting (Alt-Shift-F) We have bad hint.  
```php
$res = test($in);

function test($in)
{
	$out = preg_replace("/.*/", "+++", $in);
	return $out;
}
```
See image...
![After formatting](http://ipic.su/img/img7/fs/kiss_16kb.1510512676.png)

**Comment by bmewburn** [comment]
I think this is a vscode issue, I suggest opening an issue at https://github.com/Microsoft/vscode/issues.

I set `"intelephense.server.trace" : "verbose"` and watched the symbol definition range that was returned for functions formatted like:
```php
function test() {
    //do stuff
}
//vs
function test()
{
    //do stuff
}
```
In both cases the correct definition range was returned but vscode showed a poor ctrl hover hint for the second case.

**Comment by ValeryFVV2002** [comment]
Thanks
