### ISSUE TITLE
Request initialize failed with message: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by iscraft** [bmewburn/intelephense#71]
windows7
vscode1.18.0
Intelephense0.8.1
http://windows.php.net/downloads/releases/php-7.1.11-nts-Win32-VC14-x86.zip

1.settings.json:
{
    "php.validate.executablePath": "D:/php-7.1.11-nts-Win32-VC14-x64/php.exe",
    "workbench.colorTheme": "Monokai",
    "php.suggest.basic": false,
    "intelephense.formatProvider.enable": false
    }

2.add "D:/php-7.1.11-nts-Win32-VC14-x64" to my system path

always show error:
[PHP Intelephense]Request initialize failed with message: Path must be a string. Received undefined

**Comment by sluchznak** [comment]
Probably i wrong, but windows using `\` as directory delimiter

**Comment by iscraft** [comment]
@sluchznak 
"php.validate.executablePath": "D:\\php-7.1.11-nts-Win32-VC14-x64\\php.exe",
error still

**Comment by bmewburn** [comment]
@iscraft can you turn `intelephense.trace.server` to verbose in settings and paste startup output here? `php.validate.executablePath` is not used by the extension so this will not be the cause.

**Comment by ValeryFVV2002** [comment]
"D:\\php-7.1.11-nts-Win32-VC14-x64\\php.exe",

**Comment by ricardo-lobo** [comment]
I'm having the same issue.

```
[Trace - 14:34:51] Sending request 'shutdown - (1)'.
[Trace - 14:34:51] Received response 'shutdown - (1)' in 1ms. Request failed: Request shutdown failed with message: Cannot read property 'tables' of undefined (-32603).
```

**Comment by bmewburn** [comment]
@ricardo-lobo do you have the start of the trace. I'm interested to see if there is a `storagePath` value being sent to the server.

**Comment by ricardo-lobo** [comment]
@bmewburn this is everything I got:

![screen shot 2017-11-14 at 19 53 45](https://user-images.githubusercontent.com/21181036/32801651-94e50de6-c975-11e7-9fb8-217663664100.png)

**Comment by iscraft** [comment]
@bmewburn verbose output
[Trace - 10:14:44] Sending request 'initialize - (0)'.
Params: {
    "processId": 4440,
    "rootPath": null,
    "rootUri": null,
    "capabilities": {
        "workspace": {
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            }
        },
        "textDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "completionItem": {
                    "snippetSupport": true
                }
            },
            "hover": {
                "dynamicRegistration": true
            },
            "signatureHelp": {
                "dynamicRegistration": true
            },
            "definition": {
                "dynamicRegistration": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true
            },
            "codeAction": {
                "dynamicRegistration": true
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true
            },
            "documentLink": {
                "dynamicRegistration": true
            }
        }
    },
    "initializationOptions": {},
    "trace": "verbose"
}

**Comment by mserajnik** [comment]
I'm getting the same error message under macOS 10.13.1 when I'm opening a single file and not a folder (e.g., when I'm opening a file directly from Transmit).

I've tried setting `intelephense.trace.server` to `verbose` but I'm not getting any output at all.

There's some more output flashing when I open I file, but it gets cleared before I can copy it and the only thing that remains in the console is this:

```
[Trace - 16:14:14] Sending request 'shutdown - (1)'.
[Trace - 16:14:14] Received response 'shutdown - (1)' in 1ms. Request failed: Request shutdown failed with message: Cannot read property 'tables' of undefined (-32603).
```

**Comment by preadfish** [comment]
Same here, Windows 10, latest VScode, latest Intelephense.

`
shell.ts:459 [bmewburn.vscode-intelephense-client] Request shutdown failed with message: Cannot read property 'tables' of undefined: Error: Request shutdown failed with message: Cannot read property 'tables' of undefined
	at new ResponseError (C:\Users\swittling\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (C:\Users\swittling\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (C:\Users\swittling\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate.<anonymous> (C:\Users\swittling\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.1\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)
e.onUnexpectedError @ shell.ts:459`

**Comment by bmewburn** [comment]
Thanks for the reports everyone, v0.8.2 now handles the case where a workspace storage path is not defined (eg opening single file).
