### ISSUE TITLE
Add Use Declaration Not Working

### ISSUE THREAD

**Issue by gredenz** [bmewburn/intelephense#74]
Add Use Declaration from the context menu or keyboard shortcut does not appear to be working.

**Comment by kyrpas** [comment]
I experience the same issue

**Comment by alexciarlillo** [comment]
I am also having this issue.

**Comment by bmewburn** [comment]
This feature has had some problems in the past, I'll revisit. It will fail correctly in some situations like if there is already a use declaration of the same name or if it can't find the symbol.

**Comment by espositodaniele** [comment]
I'm having the same issue here, trying a class but it doesn't work. For example, I'm in a laravel project and I'm trying to use Request class, I type the name of the class and it doesn't work.

Any solution There??

**Comment by bmewburn** [comment]
Yet to take a look at improving this but for now there's a few things to check to get this working.
1. If you have added any php associations to `files.associations` setting, make sure you include the standard `*.php` association too. The extension must be able to find an indexed symbol for it to work.
2. The cursor must be inside or directly next to a fully qualified name and it must be a complete expression eg the fqn in `\MyNs\MyClass::MY_CONST`

**Comment by bmewburn** [comment]
Removed in 1.0 and will be reimplemented as a code lens code action in future. For now ctrl + space (or equivalent to trigger completion suggestions) will show suggestion selection which can auto add a use decl when selected.
