### ISSUE TITLE
Show all namespaces in autocomplete

### ISSUE THREAD

**Issue by Failcookie** [bmewburn/intelephense#75]
Right now, the autocomplete will only show the namespace hint on hover selection in the context menu. It would be great to be able to see this for all of the autocomplete at once for quick use imports. Specifically when I think of models and faker data that have the same class name, but different namespaces.

**Comment by bmewburn** [comment]
Unsure about this one. Originally back in the first release I had the fully qualified name showing for the completion items but found it created a disconnect between the short name I was typing and what was displayed. I do see what your saying though, at times there can be a long list of same named class. Will leave open for consideration.

**Comment by Failcookie** [comment]
I can see that being a problem. I think it would be weird to see the full name being listed right off the bat. Coming from using PHPStorm religiously, it's definitely a hard switch when I have to swift through looking through a bunch of class names like pictures below. Not a must - but definitely a nice quality of life modification, if it's something doable. Love to see what others say.

![untitled](https://user-images.githubusercontent.com/3040113/33051775-3a05574e-ce31-11e7-9730-a7d737754c65.png)

**Comment by bmewburn** [comment]
Oh, I see. Yeah the above would be nice and is doable by including this in the `label` property of the completion item. It's also something that could be implemented by the editor. The namespace string is returned in the `detail` property. So this data is available when the list appears it's just not being shown.

**Comment by Failcookie** [comment]
Looking at the editor comment, is it possible to set this as an option in the editor?

**Comment by bmewburn** [comment]
I don't think there's an option for it in vscode. I opened microsoft/vscode#39441 as I'd rather see it implemented there but we'll see.

**Comment by bmewburn** [comment]
I had an attempt at this but I found that adding the detail to the label caused issues with the label highlighting. Closing as it needs to be implemented in vscode.

![screenshot from 2018-02-07 20-07-35](https://user-images.githubusercontent.com/5885195/35943593-a97c140e-0cad-11e8-8b24-b2cd0c02cf4c.png)

**Comment by Failcookie** [comment]
Bummer :( Thank you for taking a look at this though!
