### ISSUE TITLE
Type hinting on methods

### ISSUE THREAD

**Issue by owenconti** [bmewburn/intelephense#76]
It would be ideal if the `intelephense` plugin could detect the calling of functions with incorrect arguments:

```
// Signature accepting a string...
public function acceptsAString(string $theString) {
    // do something with $theString
}

// Calling the method from somewhere...
$this->acceptsAString(123); // <- NOT A STRING!
```

If the plugin could tell me that I've passed an invalid argument, that would be awesome!

**Comment by bmewburn** [comment]
Good idea. I'd like to see this as part of the diagnostics provider.

**Comment by bmewburn** [comment]
Tracking in #16
