### ISSUE TITLE
Go to definition sometimes just don't work

### ISSUE THREAD

**Issue by psicofrenia** [bmewburn/intelephense#80]
I create a new class, add the uses clauses, and won't see any method for the objects I create from that use clauses.

```
<?php
namespace your\namespace;
use other\namespace\SomeClass;
class yourClass
{
...
$instObject = new SomeClass();
```

If I try on $instObject->, I won't see any methods.
And if I click on use other\namespace\SomeClass and choose "go to the definition", I get "No definition found for yourClass".

Sometimes this is fixed by manually "add use declaration" from context menu, sometimes it doesn't.

**Comment by bmewburn** [comment]
Are you opening a folder in vscode that contains the definitions?

**Comment by psicofrenia** [comment]
@bmewburn ,

I have open the root folder with my Symfony code, from where I can see the "src" and the "vendors".
I have also a workspace configured with some rules, none of them related to Intelephense.
Not sure if this helps, but here are my settings:

https://gist.github.com/psicofrenia/7ae8db94e8edbedd2e79173cd419b0b3

**Comment by bmewburn** [comment]
It's your `files.associations` setting. You must put the standard PHP ext in as well -- `*.php`. There was another thread with this issue, I'll have to document this better.

**Comment by psicofrenia** [comment]
I would never think of that.
Thanks for the feedback.
