### ISSUE TITLE
Request initialize failed with message: this.send is not a function

### ISSUE THREAD

**Issue by michaeljberry** [bmewburn/intelephense#83]
I encountered an error, however, it was only specific to one workspace's name. The name of the workspace was `MichaelJBerry-Space`. I can't remember at what point in my setup of Visual Studio Code (as I'm new to VSC), that this error began appearing, but I can't imagine that the error would be specific to my name, right? I haven't offended you in some way, have I? 😄 

I thought that deleting the workspace, `MichaelJBerry-Space`, and re-creating it would solve the error, but it didn't entirely. I created the workspace again for the same project and things worked just fine until I saved the workspace with the same name as before `MichaelJBerry-Space`. As soon as I saved the workspace using the same name as the previous problem workspace, I started receiving the error message again. 

So, I deleted the new workspace, `MichaelJBerry-Space`, re-created the workspace and saved it with a different name, `Michael-Space`, and now the extension's features are working without issue. I wanted to see if there was a correlation with the workspace's name and the issue, so I chose a different project, created a workspace for it and named it `MichaelJBerry-Space` and the error came back.

Any derivative of the workspace name `MichaelJBerry-Space` worked, just as long as it wasn't exactly `MichaelJBerry-Space`. It almost seems like there's a cache somewhere that says that that workspace name has issues, but I don't know for sure what's going on.

I'm running Windows 10 Education with Visual Studio Code 64bit version 1.18.1 if that helps.

The issue revolves around the initialization of your extension. I'd receive this error, but only when loading a specific workspace:

    [PHP Intelephense] Request initialize failed with message: this.send is not a function

I uninstalled all extensions except your PHP Intelephense extension and I still received the error each time I opened that specific workspace. Since I have multiple workspaces, I tried a combination of scenarios. If I opened up the workspace that was experiencing the error first, then any subsequent workspaces that I opened would also not work as expected. However, if I opened one of the other workspaces and then opened the problem workspace, the extension seemed to work well in the first workspace opened, but still not in the problem workspace.

While I don't know all of the features that your extension provides, the ones that I was using (class importing hints, variable hints, etc.) didn't populate at all. I assume that's because the initialization failed.

I opened the dev tools and restarted the problem workspace and this is the error I found:

    [bmewburn.vscode-intelephense-client] Request shutdown failed with message: this.send is not a function: Error: Request shutdown failed with message: this.send is not a function
	at new ResponseError (C:\Users\My User Name\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (C:\Users\My User Name\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (C:\Users\My User Name\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate.<anonymous> (C:\Users\My User Name\.vscode\extensions\bmewburn.vscode-intelephense-client-0.8.2\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:672:20)
	at tryOnImmediate (timers.js:645:5)
	at processImmediate [as _immediateCallback] (timers.js:617:5)

I don't know much about extension creation/debugging in Visual Studio Code, so I apologize I can't help much, but I hope this is helpful. Again, after I deleted the problem workspace and re-created it with a new workspace name, there hasn't been an issue at all. Let me know if you need any other information to help with this error.

**Comment by bmewburn** [comment]
I can confirm there is no code in there to throw errors for users named MichaelJBerry 😆 . Strange that it seems to be the folder name that causes issues. At at guess there may be some old cached data in the workspace storage dir that is not compatible with recent updates of the ext. To troubleshoot further you could set `"intelephense.trace.server" : "verbose"` and look at the output at extension startup for any other errors. You will also be able to see the value of `storagePath` and can then delete the extension specific contents of this directory. Other solutions include changing your name with your government registrar 😄

**Comment by michaeljberry** [comment]
This is what I found. It looks like there's another error, but I can't determine if it's related and/or the cause of the previous error.

    exitCode: 128
    message: "Git error"
    stderr: "fatal: Pathspec 'c:\Users\My User Name\path\to\project\michaeljberry\webpack.mix.js' is in submodule 'michaeljberry'"
    stdout: ""

Any ideas? It seems that anytime I scroll through the explorer, a similar error occurs - all referencing the Pathspec being in submodule "michaeljberry".

**Comment by bmewburn** [comment]
Looks like your git is messed up. I'm unsure if it is related.

**Comment by michaeljberry** [comment]
I finally found the `storagePath` property you referred to. I kept looking in the developer tools window, but it was in the output window in VSC. I deleted the extension specific information in the folder and it works just fine now. Thank you for your help!
