### ISSUE TITLE
backslash when autocompleting

### ISSUE THREAD

**Issue by alanaasmaa** [bmewburn/intelephense#86]
Hi, when i use autocomplete it automatically adds `\` in front of core PHP functions.

Why does it do like this and is there a way to turn it off 

```
        if (\is_numeric($number)) {
            //
        }
```

**Comment by bmewburn** [comment]
Having the backslash explicitly identifies the global namespaced function and prevents a second symbol lookup when resolving. If preferred you can set `intelephense.completionProvider.backslashPrefix` to false in the settings to turn it off.
