### ISSUE TITLE
Formatting and PSR-2: arguments on multiple lines

### ISSUE THREAD

**Issue by mcdado** [bmewburn/intelephense#96]
Hello, I arrived here after looking at the [extension page on the marketplace](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client).

I found it to be quite useful alongside this other extension: [ikappas.phpcs](https://marketplace.visualstudio.com/items?itemName=ikappas.phpcs).

I have one problem with formatting though: in a method declaration if I break arguments on multiple lines, phpcs configured to use PSR2 wants me to put the opening `{` on the same line of the closing `)`, while the formatting from this extension puts the `{` on a new line. Since in https://github.com/bmewburn/intelephense/issues/51 you mentioned that this extension for now uses PSR2, it does not seem to respect the rule regarding arguments on multiple lines defined here: [PSR-2: Coding Style Guide - PHP-FIG](http://www.php-fig.org/psr/psr-2/#44-method-arguments).

**Comment by bmewburn** [comment]
thanks for reporting. resolved in v0.8.3
