### ISSUE TITLE
Unclear error: "[intelephense] Unexpected Unknown."

### ISSUE THREAD

**Issue by BLaDZer** [bmewburn/intelephense#98]
Strange error occurs when I use non-Latin characters in the naming of variables and methods. Though http://php.net/manual/en/language.variables.basics.php says everything should be fine:

> Variable names follow the same rules as other labels in PHP. A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: '[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'

At least we need a proper hint for this error message.

**Comment by BLaDZer** [comment]
Also after project indexing is complete this error doesn't appear until I modify(save) a problem file. This strange I think.

**Comment by bmewburn** [comment]
![screenshot from 2017-12-15 21-58-11](https://user-images.githubusercontent.com/5885195/34039372-5116621e-e1e3-11e7-8c29-4696dedcce2f.png)

The lexer uses the range as specified in the PHP spec. What's the character it doesn't like and the encoding?

**Comment by BLaDZer** [comment]
![screenshot from 2017-12-15 15-27-48](https://user-images.githubusercontent.com/13044587/34040405-fe378c52-e1ac-11e7-9b51-fc4d5543328b.png)
russian/japanese
utf-8

**Comment by BLaDZer** [comment]
With extension https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense these names also valid.

**Comment by bmewburn** [comment]
You dont have a `u` modifier on your regular expressions http://php.net/manual/en/reference.pcre.pattern.modifiers.php

I think php support for characters > \xff is a side effect of it not properly handling multibyte encoding (or the docs are unclear). I can relax this in the lexer to match what the official php parser does.

**Comment by bmewburn** [comment]
resolved in v0.8.3
