### ISSUE TITLE
Include "files.associations" but not replace when indexing files

### ISSUE THREAD

**Issue by BLaDZer** [bmewburn/intelephense#99]
Ok I found bug and solution. Not working autocomplete was caused by the fact that I used a non-standard file extension for php in the settings "files.associations".

Seems that you used it only for project indexing instead extending it with default "*.php" extension. So I have to edit this config from:
```
    "files.associations": {
        "*.inc": "php"
    },
```
to
```
    "files.associations": {
        "*.inc": "php",
        "*.php": "php"
    },
```

Thnx to debug output :)

Can you fix it please?

**Comment by BLaDZer** [comment]
Ok I found bug and solution. This bug was caused by the fact that I used a non-standard file extension for php in the settings "files.associations".

Seems that you used it only for project indexing instead extending it with default "*.php" extension. So I have to edit this config from:
```
    "files.associations": {
        "*.inc": "php"
    },
```
to
```
    "files.associations": {
        "*.inc": "php",
        "*.php": "php"
    },
```

Thnx to debug output :)

Can you fix it please?

**Comment by BLaDZer** [comment]
https://github.com/bmewburn/vscode-intelephense/blob/master/client/src/extension.ts#L177

Hmm, maybe this already fixed but not released or..?

**Comment by BLaDZer** [comment]
last release v0.8.2 - 27 days ago

https://github.com/bmewburn/vscode-intelephense/commit/8e3831519c22e0268fcdecff6e0b332207ec303c - 15 days ago

ok maybe it's would be fine now

**Comment by bmewburn** [comment]
Yes, this is fixed and will be recently soon.
